name: Air carrier management

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get install build-essential

    - name: Build project using Make
      run: |
        make  

    - name: Run unit tests
      run: |
        ./bin/test_helicopter_flight_hours

    - name: Clean up build files
      run: make clean

